kafka_network_name: kafka-net
kafka_zookeeper_image: "bitnami/zookeeper:3.9-debian-12"
kafka_image: "bitnami/kafka:3.7-debian-12"
kafka_container_name: kafka
zookeeper_container_name: zookeeper
kafka_topic_whatsapp: whatsapp-messages

